### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by nin0-dev** [StupidityDB/Website#8]
![image](https://github.com/StupidityDB/Website/assets/75569739/41e77220-8d68-48aa-bf11-a95e48c5ac68)

You will fix

**Comment by RGBCube** [comment]
works fine

**Comment by nin0-dev** [comment]
i know

mantika just did insane stuff with ssl so it broke

next time he will test on ven's domain

**Comment by RGBCube** [comment]
he will stop using caddy and use nginx with acme.sh on a timer managed by NixOS

**Comment by mantikafasi** [comment]
I am not even using caddy, its ran on cloudflare pages(thanks to oracle nuking my vps)
